Add README to introduce the background of HP++
kaist-cp/hp-plus pull request #1
Opened 2023-05-01 06:49 UTC by powergee

Rendered: https://github.com/powergee/hp-plus/blob/main/README.md

* 원 논문을 기초로, Introduction과 API description을 작성하였습니다.
* Harris's list을 test로 추가하고 README에서 이를 언급해두었습니다.

> You can check the actual implementation of *Harris's list* in *tests/harris_list.rs*.

2023-05-01 07:29 UTC, Lee-Janggun requested changes

2023-05-01 07:29 UTC, Lee-Janggun commented on README.md
> +### TryProtect
* 이름이 밑의 코드랑 안 맞는건 이상합니다.
* pp가 뭐의 약자인지 모르니까 한번 풀어 써 줍시다.

2023-05-01 07:29 UTC, Lee-Janggun commented on tests/harris_list.rs
> +}
Newline for EOF.

2023-05-01 07:29 UTC, Lee-Janggun commented on tests/harris_list.rs
> +    anchor: Option<(*mut Node<K, V>, *mut Node<K, V>)>,
이걸 cursor에 넣는건 좀 이상한거 같습니다.

2023-05-01 07:43 UTC, powergee commented on README.md
> +### TryProtect
Rust 코드에서 명명하는 방식대로 맞추고, 각각이 논문에서 말하는 TryProtect, TryUnlink에 대응된다는 말을 추가했습니다.

> This crate provides two major APIs: `try_protect_pp` and `try_unlink`, corresponding to **TryProtect** and **TryUnlink** in the original paper, respectively.
>
> (`.._pp`, which stands for *plus-plus*, is used in `try_protect_pp` to distinguish with `try_protect` function that provides HP version of protecting.)

2023-05-01 07:43 UTC, powergee commented on tests/harris_list.rs
> +}
`cargo fmt`로 일괄 수정했습니다.

2023-05-01 08:30 UTC, tomtomjhj commented on README.md
> +We design **HP++, a backward-compatible extension for HP** to improve applicability by enabling optimistic traversal. The key idea is *under-approximating* the unreachability in validation to allow o
HP++ is a backward-compatible extension for HP

2023-05-01 08:49 UTC, powergee commented on README.md
> +We design **HP++, a backward-compatible extension for HP** to improve applicability by enabling optimistic traversal. The key idea is *under-approximating* the unreachability in validation to allow o
두번째 문단만 남기고 적어주신 문장을 첫 문장으로 하여 재작성해보았는데 확인부탁드립니다.

2023-05-01 09:01 UTC, Lee-Janggun approved these changes

2023-05-02 01:54 UTC, powergee commented
Zulip에서 공유해드린 memory alignment 이슈도 해결해서 커밋했습니다.

* `List`의 `Node`에 `#[repr(C)]` 추가

2023-05-02 02:24 UTC, tomtomjhj requested changes

2023-05-02 02:24 UTC, tomtomjhj commented on README.md
> +(`.._pp`, which stands for *plus-plus*, is used in `try_protect_pp` to distinguish with `try_protect` function that provides HP version of protecting.)
distinguish it from

2023-05-02 02:24 UTC, tomtomjhj commented on README.md
> +**HP++ is a backward-compatible extension for HP**, which improve applicability by enabling optimistic traversal. The key idea is *under-approximating* the unreachability in validation to allow *opti
hazard pointers (HP)

2023-05-02 02:24 UTC, tomtomjhj commented on README.md
> +2. `frontier`: the pointers that the unlinker has to protect for the traversing threads.
논문의 Frontier 문단 내용도 써주는거ㅔ 좋겠스빈다

2023-05-02 02:24 UTC, tomtomjhj commented on tests/harris_list.rs
> +    /// tag 1: logically deleted, tag 2: stopped
invalidated

2023-05-02 02:57 UTC, powergee commented
@tomtomjhj Frontier 관련 설명을 추가했습니다.

2023-05-02 04:21 UTC, merged